### ISSUE TITLE
Fracción propia o impropia

### ISSUE THREAD

**Issue by joaquinz916** [joaquin-z/IWVG.SwC.Joaquin#1]
Crear los métodos necesarios para saber si una funcion es propia o impropia

[Más información](https://github.com/joaquin-z/IWVG.SwC.Joaquin/wiki/Clase-DecimalCollection)

**Comment by angelmart** [comment]
Creados los métodos isPropia, isImpropia que devuelven si una fracción es propia o impropia.

Creados los test correspondientes.
