### ISSUE TITLE
Método para multiplicar

### ISSUE THREAD

**Issue by joaquinz916** [joaquin-z/IWVG.SwC.Joaquin#4]
Incluir el método de multiplicar en la clase DecimalCollection

[Más información](https://github.com/joaquin-z/IWVG.SwC.Joaquin/wiki/Clase-DecimalCollection)

**Comment by rploaiza** [comment]
Método añadido y pasan los test

**Comment by joaquinz916** [comment]
El sonar me detecta algo de smell code pero nada mas alla de lo que se muestra en la imagen, el valor esperado deberia ser decimal asi como la funcion de arriba, abrire un nuevo issue para darle solucion.

![imagen](https://user-images.githubusercontent.com/9363523/30654639-c98488aa-9e2e-11e7-8929-4f2896c6b3a1.png)

**Comment by rploaiza** [comment]
Si se esta multiplicando si revisas el código cumple con el test y te da el resultado o quieres que cambie a -12.0 el valor de comprobación ?
