### ISSUE TITLE
Mejora para metodo isIndefinite()

### ISSUE THREAD

**Issue by joaquinz916** [joaquin-z/IWVG.SwC.Joaquin#8]
El sonar dice que el test no esta cubierto en una condicion, ademas de esto dice que se puede resumir toda la condicion en una sola linea retornando solo la condicion, asi te evitas el if-else, aun asi el test del sonar ha pasado y esta correcto pero se podria mejorar el porcentaje de cobertura

![imagen](https://user-images.githubusercontent.com/9363523/30709053-30663c3a-9f01-11e7-8c07-7a70947ae2b4.png)

**Comment by rafaelfalconi** [comment]
Correcciones realizadas
